import = [
	"~/.config/alacritty/hyper.toml"
]

shell = "zsh"

[window]
opacity = 0.8
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono NFM", style = "Medium" }
bold = { family = "JetBrainsMono NFM", style = "Bold" }
italic = { family = "JetBrainsMono NFM", style = "Italic" }
bold_italic = { family = "JetBrainsMono NFM", style = "Bold Italic" }
size = 10.0

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 0
thickness = 0.2
